### ISSUE TITLE
[request] Call out my Steam Deck modpack

### ISSUE THREAD

**Issue by Merith-TK** [PolyMC/polymc.github.io#173]
https://github.com/PolyMC/polymc.github.io/blob/master/src/wiki/getting-started/controller-support.md

I was hoping my steam deck modpack could be given an shout out here as it is built specifically to function well with the Steam Deck , as well as other controllers

https://github.com/Merith-TK/mc-steamdeck-modpack

**Comment by ZekeSmith** [comment]
Unlikely, I am going to start work on an official deck mod for PolyMC with Dada for testing. You are welcome to join the efforts and it would be greatly appreciated. 

I also want to discuss with the maintainers of implementing a modules feature in which you could extend functionality in any modpack or instance instead of requiring a specific instance for a feature like controller support.
